### ISSUE TITLE
设置默认值怎么设置？

### ISSUE THREAD

**Issue by chinavane** [Plortinus/element-china-area-data#1]
我看默认值都是空的，尝试设置了一下默认值也不行。

**Comment by chinavane** [comment]
默认值设置      selectedOptions:[["130000","河北省"],["130300","秦皇岛市"],["130304","北戴河区"]] 类似这样，不显示选中的。

**Comment by Plortinus** [comment]
@chinavane `selectedOptions`数值类型得设置成elementUI的级联插件那样的数据

**Comment by Plortinus** [comment]
http://jsfiddle.net/50bvy1rh/ 我试着他们的组件的value不支持数组

**Comment by Plortinus** [comment]
@chinavane 已fixed，添加了区域码转汉字的一个对象
