### ISSUE TITLE
v-model双向绑定三级菜单区域码问题

### ISSUE THREAD

**Issue by lanjincan** [Plortinus/element-china-area-data#11]
请问为什么v-mode绑定三级的code不能显示在选择框里面 但是获取一级的code就可以，我应该怎么写才能把三级菜单渲染上选择框里面呢？
![qq 20180504192710](https://user-images.githubusercontent.com/38325607/39625691-2f8fc12e-4fd1-11e8-9db0-a4d22d816745.png)
![qq 20180504192717](https://user-images.githubusercontent.com/38325607/39625693-31473ea2-4fd1-11e8-92c6-43403be811a3.png)

**Comment by lanjincan** [comment]
我把区域码手动v-model了 但是三级的显示不出来 一级的可以 应该怎么解决呢

**Comment by Plortinus** [comment]
vmodel的数组里放三个值，第一个是省code第二个是市，第三个是区
