### ISSUE TITLE
可以提供只显示区域名称的数据出来么

### ISSUE THREAD

**Issue by xiaofan9** [Plortinus/element-china-area-data#16]
可以提供只显示区域名称的数据出来么

**Comment by xiao-ma-nong** [comment]
怎么捣腾这个问题，value是获取的数字代码，怎么获取中文呢

**Comment by xiaofan9** [comment]
> 怎么捣腾这个问题，value是获取的数字代码，怎么获取中文呢

建议通过ref，拿到组件内部的数据，然后用关联value，查出对应的名称

**Comment by xiao-ma-nong** [comment]
也不用了，直接在 用内置方法，刚刚看了文档
