### ISSUE TITLE
根据已存汉字初始化显示

### ISSUE THREAD

**Issue by chunliangl** [Plortinus/element-china-area-data#2]
我库里将省和市分开存成汉字，请问怎么能根据汉字初始化值？

**Comment by Plortinus** [comment]
这个得需要自己写一个大点对象(属性是汉字,值是区域码),将汉字转换成区域码,然后才能用这个包做初始化值.
或者你自己fork一份,改改

**Comment by chunliangl** [comment]
好的，谢谢！
