### ISSUE TITLE
el-cascader input框与下拉框显示的数据不对

### ISSUE THREAD

**Issue by qinyure** [Plortinus/element-china-area-data#36]
当查看下一个省市区的时候，v-model="selectedOptions"绑定的数据是对的，下拉框显示的是上一个查看的数据且区是没有绑定的

**Comment by Plortinus** [comment]
https://plortinus.github.io/element-china-area-data/index.html 我看demo里没问题，你用的element ui版本是多少？会不会是版本的问题？

**Comment by qinyure** [comment]
加了一个v-if好了，组件需要重新渲染

**Comment by alicksnake22** [comment]
@Plortinus 的确是这样，绑定的数量以及input框显示的是对的，但是展开后打钩的显示的是上一个输入的数据，没刷新，能修复下吗

**Comment by Fomovet** [comment]
最新版本也是遇到同样问题
