### ISSUE TITLE
在nuxt.js中使用报Window未定义

### ISSUE THREAD

**Issue by EagleCQ** [Plortinus/element-china-area-data#37]
虽然按照nuxt官网中给的解决方法弄好了，不知作者有没有考虑兼容下服务端呢
[nuxt的解决方法](https://www.nuxtjs.cn/faq/window-document-undefined)

**Comment by Plortinus** [comment]
这个包兼容服务端，服务端的用法代码参考是
`const { provinceAndCityData } = require('element-china-area-data/dist/app.commonjs')`
