### ISSUE TITLE
IE11 引用出现 SCRIPT1053: 必须初始化 Const

### ISSUE THREAD

**Issue by kwun12** [Plortinus/element-china-area-data#38]
IE11 引用出现 SCRIPT1053: 必须初始化 Const

**Comment by pasBone** [comment]
可以指定一下 babel targets  到 ie9

**Comment by pasBone** [comment]
或者是设置 vue.config.js transpileDependencies 选项。就可以编译到目标浏览器了。

**Comment by Mrs-suo** [comment]
你好,解决了吗

**Comment by Mrs-suo** [comment]
> 可以指定一下babel目标到ie9

你好,设置这个后还是同样的错误,请问下具体是怎么解决的吗,谢谢

**Comment by pasBone** [comment]
> > 可以指定一下babel目标到ie9
> 
> 你好,设置这个后还是同样的错误,请问下具体是怎么解决的吗,谢谢
vue.config.js 添加一项配置。
`
  transpileDependencies: [
    'element-china-area-data'
  ]
`
顺便说一句，IE真恶心

**Comment by Plortinus** [comment]
已修复

**Comment by wjh0309** [comment]
vue2.x上要怎么改
