### ISSUE TITLE
绑定的数据与显示的数据有误

### ISSUE THREAD

**Issue by alicksnake22** [Plortinus/element-china-area-data#39]
绑定的数据以及input框显示的是对的，但是展开后打钩的显示的是上一个输入的数据，没刷新，能修复下吗。已有人提过同样问题。
![image](https://user-images.githubusercontent.com/14839142/93671889-4a52a980-fad9-11ea-85d4-e13c8bb2d096.png)

**Comment by Fomovet** [comment]
同问

**Comment by Plortinus** [comment]
https://github.com/ElemeFE/element/issues/20112

这个应该是element组件的bug，和数据无关

**Comment by Fomovet** [comment]
解决办法：https://github.com/ElemeFE/element/issues/18669#issuecomment-643733509
打开编辑窗口的时候先清空一下前面的数据和状态
