### ISSUE TITLE
部分省级数据缺失

### ISSUE THREAD

**Issue by pl1998** [Plortinus/element-china-area-data#60]
![image](https://user-images.githubusercontent.com/43993206/125913933-cd655953-4a35-40eb-a254-6d4312b9b90b.png)
为什么数据缺失
![image](https://user-images.githubusercontent.com/43993206/125914053-18d8f210-782b-4d28-900a-3aaa663036d7.png)

**Comment by Plortinus** [comment]
v6里更换了数据源
