### ISSUE TITLE
使用的时候能显示地区选择但是,控制台报错,而且CodeToText好像是undefined

### ISSUE THREAD

**Issue by konanzheng** [Plortinus/element-china-area-data#7]
`
isURLSameOrigin.js?2db6:57 Uncaught (in promise) TypeError: Cannot read property 'protocol' of undefined
    at isURLSameOrigin (isURLSameOrigin.js?2db6:57)
    at dispatchXhrRequest (xhr.js?a790:108)
    at new Promise (<anonymous>)
    at xhrAdapter (xhr.js?a790:12)
    at dispatchRequest (dispatchRequest.js?5c70:52)
    at <anonymous>
isURLSameOrigin @ isURLSameOrigin.js?2db6:57
dispatchXhrRequest @ xhr.js?a790:108
xhrAdapter @ xhr.js?a790:12
dispatchRequest @ dispatchRequest.js?5c70:52
Promise rejected (async)
getData @ edit-print-factory.vue?2376:98
boundFn @ vue.common.js?62e1:193
created @ edit-print-factory.vue?2376:83
callHook @ vue.common.js?62e1:2897
Vue._init @ vue.common.js?62e1:4562
VueComponent @ vue.common.js?62e1:4730
createComponentInstanceForVnode @ vue.common.js?62e1:4244
init @ vue.common.js?62e1:4061
createComponent @ vue.common.js?62e1:5514
createElm @ vue.common.js?62e1:5462
updateChildren @ vue.common.js?62e1:5751
patchVnode @ vue.common.js?62e1:5842
updateChildren @ vue.common.js?62e1:5728
patchVnode @ vue.common.js?62e1:5842
patch @ vue.common.js?62e1:6002
Vue._update @ vue.common.js?62e1:2649
updateComponent @ vue.common.js?62e1:2767
get @ vue.common.js?62e1:3117
run @ vue.common.js?62e1:3194
flushSchedulerQueue @ vue.common.js?62e1:2956
(anonymous) @ vue.common.js?62e1:1815
flushCallbacks @ vue.common.js?62e1:1736
module.exports @ _invoke.js?53ac:5
queue.(anonymous function) @ _task.js?71e9:35
run @ _task.js?71e9:21
listener @ _task.js?71e9:25
vue.common.js?62e1:580 [Vue warn]: Error in event handler for "change": "TypeError: Cannot read property '110000' of undefined"

found in

`
![_006](https://user-images.githubusercontent.com/3112689/34820288-05fe843c-f6fb-11e7-95b4-22aa0589820e.png)

**Comment by Plortinus** [comment]
看不出是什么问题，提供一下简要可复现的项目代码吧

**Comment by konanzheng** [comment]
我又仔细看了不是组件的问题,是我代码的问题,不好意思打扰了

**Comment by wodepig** [comment]
哎呀,解决了就说下怎么解决的啊,晕

**Comment by wodepig** [comment]
> 哎呀,解决了就说下怎么解决的啊,晕

CodeToText[]是方括号,不是()小扩号.我是sb,完结
