### ISSUE TITLE
报错提示codeToText is not a function

### ISSUE THREAD

**Issue by loveextra** [Plortinus/element-china-area-data#90]
在ruoyi.ts 工具函数中使用codeToText函数，但是报错提示codeToText is not a function

![image](https://github.com/Plortinus/element-china-area-data/assets/11678261/b8f30ba3-2dd8-47c0-84f0-c27d5f997781)
![image](https://github.com/Plortinus/element-china-area-data/assets/11678261/b26dff1b-c33d-447b-a2a4-2d3acf2d3be3)
![image](https://github.com/Plortinus/element-china-area-data/assets/11678261/36730f76-cafe-46bf-8e8d-63ebb02ed08a)

**Comment by vv1vv2** [comment]
本来就不是函数，是个键值对。

**Comment by loveextra** [comment]
抱歉。没有认真看文档，把codeToText当函数用了 ^_^。【codeToText是个大对象，属性是区域码，属性值是汉字】。

![微信截图_20231011155655](https://github.com/Plortinus/element-china-area-data/assets/11678261/079eb0de-984c-412d-b244-0fba1608f700)
